["protostar.config"]
protostar_version = "0.3.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
main = [
    "src/main.cairo",
]

["protostar.shared_command_configs"]
cairo-path = ["src", "lib/cairo_streams/src"]
